# Generated by Django 5.2.8 on 2025-11-27 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('contact_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_ID', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organizer_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.contact_person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity_Schedule',
            fields=[
                ('schedule_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_participants', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.activity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.location')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('participant_type', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Booking',
            fields=[
                ('booking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('has_attended', models.BooleanField()),
                ('booking_date', models.DateField()),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.activity_schedule')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.participant')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.room'),
        ),
    ]
