# Generated by Django 5.2.8 on 2025-11-28 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)])),
                ('building_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={},
        ),
        migrations.RenameField(
            model_name='contact_person',
            old_name='contact_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='address',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact_person',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_person',
            name='middle_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='max_capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='middle_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity_booking',
            name='booking_ID',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='activity_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity_schedule',
            name='schedule_ID',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='contact_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Contact number must be in XXX-XXX-XXX format', regex='^\\d{3}-\\d{3}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='contact_person_id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_ID',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organizer_id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organizer_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_ID',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_type',
            field=models.CharField(choices=[('ST', 'Student'), ('FM', 'Faculty'), ('SM', 'Staff Member')], max_length=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.building'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
