# Generated by Django 5.2.8 on 2025-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='contact_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='contact_number',
            field=models.IntegerField(default=9277902189),
            preserve_default=False,
        ),
    ]
