# Generated by Django 5.1.5 on 2025-11-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='contact_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='contact_number',
            field=models.IntegerField(default=911911),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_type',
            field=models.CharField(max_length=255),
        ),
    ]
