# Generated by Django 5.2.8 on 2025-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_contact_person_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_type',
            field=models.CharField(max_length=255),
        ),
    ]
