# Generated by Django 5.2.8 on 2025-11-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_participant_participant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_schedule',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity_booking',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='activity_booking',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='activity_schedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='activity_schedule',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Activity_Booking',
        ),
        migrations.DeleteModel(
            name='Activity_Schedule',
        ),
        migrations.DeleteModel(
            name='Contact_Person',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
